### ISSUE TITLE
Random Infinity or Weapon Mods?

### ISSUE THREAD

**Issue by KSGaming96** [KSGaming96/miningBelt#1]
@RJS1997 **and everyone else** *<3*

**I'm at a pretty stable position on my build right now.**

*I want to go both ways eventually, but I wanted to see what you'd like to see first.*

**1. Infinite Galaxies**
* Would just keep weapons as a basic single shot energy and missile that can be hot-swapped.
* Add a local star and asteroid generation script with spawning chunks to turn it into an infinite galaxy.

**2. Modular Weapons**
* Add weapon mod support. Split, spread, and stagger mods will change bullets real-time. 
* Should look pretty cool. Will add at least two more colorful energy weapons and two missiles as well. 

I will be adding a planet where you can buy and sell goods. 
* Option 1: will spawn planets randomly as the galaxy expands.
* Option 2: will just have one planet, in the current 2x2 chunk area.

*Also adding collisions with asteroids so you'll have to be careful when mining.*

**Comment by RJS1997** [comment]
Well I am leaning more towards modular weapons just so if you still plan to release its first alpha soon it will give more content for people to experience and I just want to shoot colors :D . Otherwise if you decided to wait a bit for whatever reason I would work on the infinite galaxies first just to get that out of the way and will let you focus more on future content.

**Comment by KSGaming96** [comment]
Implementing more weapons! Thanks RJ <3
